/*
 * generated by Xtext
 */
package ttc.testdsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import ttc.testdsl.services.TTCTestGrammarAccess;

public class TTCTestParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TTCTestGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected ttc.testdsl.parser.antlr.internal.InternalTTCTestParser createParser(XtextTokenStream stream) {
		return new ttc.testdsl.parser.antlr.internal.InternalTTCTestParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Test_File";
	}
	
	public TTCTestGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TTCTestGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
