/*
 * generated by Xtext
 */
package ttc.testdsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TTCTestRuntimeModule extends ttc.testdsl.AbstractTTCTestRuntimeModule {

}
