/*
* generated by Xtext
*/
package ttc.testdsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TTCTestStandaloneSetup extends TTCTestStandaloneSetupGenerated{

	public static void doSetup() {
		new TTCTestStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

